[toolchain]
anchor_version = "0.31.1"
solana_version = "2.3.0"

[provider]
cluster = "localnet"
wallet  = "/Users/$(whoami)/.config/solana/id.json"

[programs.localnet]
merkle_distributor = "EvmP5JK19rxaDE46CbP3dkVUPUCP33GohhUf2Xxu9jMs"
