[package]
name = "merkle-distributor"
version = "0.0.1"
description = "A Solana program for distributing tokens according to a Merkle root."
edition = "2021"
repository = "https://github.com/jito-foundation/governance"
authors = ["Jito Foundation <team@jito.network>"]
license = "GPL-3.0"

[lib]
crate-type = ["cdylib", "lib"]
name = "merkle_distributor"
path = "src/lib.rs"

[features]
no-entrypoint = []
no-idl = []
cpi = ["no-entrypoint"]
default = []

[dependencies]
anchor-lang = "0.31"
anchor-spl  = "0.31"
bytemuck    = "1"
solana-security-txt = "1.1"
jito-merkle-verify = { path = "../../verify" }

